name: baremetal_audio
description: A high-performance, lock-free audio DSP engine using C++17 and Miniaudio via Dart FFI.
version: 1.0.2
homepage: https://github.com/Nimakharraji/BareMetal_Audio
repository: https://github.com/Nimakharraji/BareMetal_Audio
issue_tracker: https://github.com/Nimakharraji/BareMetal_Audio/issues
license: Apache-2.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # FFI for C++ Interop
  ffi: ^2.1.2
  
  # State Management (Updated to latest versions to fix pub.dev penalty)
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.baremetal_audio
        pluginClass: BaremetalAudioPlugin